### ISSUE TITLE
Тут по ссылке стоит передать массив. или же вынести его в поле обьекта. тогда условие с его изменением - решится.

### ISSUE THREAD

**Issue by paladinbbk** [kmorenov/hillel#1]
https://github.com/kmorenov/hillel/blob/e1b3d848dbce48d3ee8b93b55407d28dce55f8ba/hw1_part1.php#L36

**Comment by kmorenov** [comment]
Thanks for the idea,but passing array by reference does not fix the issue of value conversion 

public function elemReplace(&$arr, $z, &$i)
    {
        foreach ($arr as $a) {
            if ($a > $z) {
                $arr = str_replace($a, $z, $arr);
                $i++;
            }
        }

        return $arr;

/*        foreach ($arr as $a) {
            $arr_int[] = intval($a);
        }
        return $arr_int;*/
    }

**Comment by paladinbbk** [comment]
тут решение неверное. str_replace для строк. а не для массивов или чисел

**Comment by paladinbbk** [comment]
ожидал подобное решение 
http://joxi.ru/8AnzYVYcqll6jA
