### ISSUE TITLE
Убрать из этого файла/класса задачу фибоначи. оставить только с массивами. переименовать объект и занести массив в поле объекта.

### ISSUE THREAD

**Issue by paladinbbk** [kmorenov/hillel#2]
https://github.com/kmorenov/hillel/blob/e1b3d848dbce48d3ee8b93b55407d28dce55f8ba/hw1_part1.php#L3

**Comment by kmorenov** [comment]
Completed the requested changes. Array became object property. Moved Fibonacci method to the Second.php file.
